USE SWIFT_BACKEND;

CREATE TABLE USER (
	ID BINARY(16) NOT NULL PRIMARY KEY,
	NAME VARCHAR(15) NOT NULL,
	LASTNAME VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD TEXT NOT NULL
);

CREATE TABLE POST (
	ID BINARY(16) NOT NULL PRIMARY KEY,
	USER_ID BINARY(16) NOT NULL,
	TITLE TEXT NOT NULL,
	DESCRIPTION TEXT,
	POST_DATE DATE,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE ROLES (
	ROLE_ID BINARY(16) NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL
);

CREATE TABLE USER_ROLES (
	USER_ROLE_ID BINARY(16) NOT NULL PRIMARY KEY,
	ROLE_ID BINARY(16) NOT NULL,
	USER_ID BINARY(16) NOT NULL,
	FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);


INSERT INTO ROLES (ROLE_ID, NAME) 
	VALUES (UUID_TO_BIN(UUID(), 1), "USER"), (UUID_TO_BIN(UUID(), 1), "ADMIN");


SELECT * FROM USER;
SELECT * FROM POST;
SELECT * FROM ROLES;
SELECT * FROM USER_ROLES;

DELETE FROM USER;
DELETE FROM POST;
DELETE FROM USER_ROLES;
DELETE FROM ROLES;



SHOW DATABASES;

CREATE DATABASE SWIFT_BACKEND_TEST;
USE SWIFT_BACKEND_TEST;